### ISSUE TITLE
Hello, which paper of yours is this work for?

### ISSUE THREAD

**Issue by CJ0510** [BJCaasenbrood/soft-robot-model-MATLAB#1]
Hello, which paper of yours is this work for?

**Comment by BJCaasenbrood** [comment]
The paper can be found here [Link](https://www.researchgate.net/publication/361522542_Control-Oriented_Models_for_Hyperelastic_Soft_Robots_Through_Differential_Geometry_of_Curves?_sg%5B0%5D=_tl6GlQJ47rjJ2bTCCrAPzGNH1AOrkWxm6PEqlk79z6OHQruXMoavTuaGj2P3amtet39SufuNeWz_7otxZf08NiAYLku9Glv0T4dcuNE.WlnR8ANBJGTcrrilVAP2yd8YZewqs0Nam_XTQ6URPYMDSUmdOX5VFHclOADUenP7GVh-Z0bxi2sDIYnz6DfPwQ&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImhvbWUiLCJwYWdlIjoicHJvZmlsZSIsInByZXZpb3VzUGFnZSI6InByb2ZpbGUiLCJwb3NpdGlvbiI6InBhZ2VDb250ZW50In19)

If you send me a reading request on ResearchGate, I can share a private version of the paper.
