### ISSUE TITLE
Hello, author, I am also a soft robot. Is there a corresponding paper for this?

### ISSUE THREAD

**Issue by CJ0510** [BJCaasenbrood/soft-robot-model-MATLAB#2]
Hello, author, I am also a soft robot. Is there a corresponding paper for this?

**Comment by BJCaasenbrood** [comment]
You asked the same question three weeks ago XD. The paper can be found here: https://www.liebertpub.com/doi/10.1089/soro.2021.0035

**Comment by CJ0510** [comment]
Thanks a lot

**Comment by BJCaasenbrood** [comment]
If you don't have access to Soft Robotics journal, let me know I can send you a private version.
